name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: terraform-linters/setup-tflint@v4
      - uses: bridgecrewio/checkov-action@master
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
